nombre ="Fabian  silva"

print(nombre.replace("Fabian silva","yamid")) 

# Ejemplos de operadores aritméticos
x = 10
y = 3
print(x + y)   # 13
print(x - y)   # 7
print(x * y)   # 30
print(x / y)   # 3.333...
print(x % y)   # 1
print(x ** y)  # 1000
print(x // y)  # 3
            

# Ejemplos de operadores de comparación
a = 5
b = 10
print(a == b)   # False
print(a != b)   # True
print(a > b)    # False
print(a < b)    # True
print(a >= b)   # False
print(a <= b)   # True

# Ejemplos de operadores lógicos
a = True
b = False
print(a and b)  # False
print(a or b)   # True
print(not a)    # False

# Ejemplos de operadores de asignación
x = 5
x += 3   # x = x + 3 -> x es ahora 8
x -= 2   # x = x - 2 -> x es ahora 6
x *= 4   # x = x * 4 -> x es ahora 24
x /= 6   # x = x / 6 -> x es ahora 4.0

